@startuml
actor Руководитель
participant Система
participant Задание

Руководитель -> Система: ВыдатьЗадание(Название, Описание)
activate Система
Система -> Задание: СоздатьЗадание(Название, Описание)
activate Задание
Система --> Руководитель: Подтверждение
deactivate Система
Руководитель --> Задание: ПолучитьЗадание()
activate Задание
@enduml
