@startuml
package "Система учета рабочего времени" {
  class Руководитель {
    +ВыдатьЗадание()
    +ОтслеживатьХодВыполнения()
  }

  class Исполнитель {
    +ВестиУчетВремени()
  }

  class Задание {
    +Название
    +Описание
    +Статус
  }

  Руководитель --> Задание
  Исполнитель --> Задание
}
@enduml
