@startuml
participant Исполнитель
participant Система
participant Задание

Исполнитель -> Система: ВестиУчетВремени(Задание, ЗатраченноеВремя)
activate Система
Система -> Задание: ЗаписатьВремя(Задание, ЗатраченноеВремя)
activate Задание
Система --> Исполнитель: Подтверждение
deactivate Система
Исполнитель --> Задание: ПолучитьСтатус()
activate Задание
@enduml
